### ISSUE TITLE
API doesn't work from IRB or Rails

### ISSUE THREAD

**Issue by jancel** [Insightly/ruby#17]
I installed the gem via bundler, and following the instructions, I type: 

```
Insightly.api_key = "test" # or whatever
```

I get this error:

```
NoMethodError: undefined method `api_key=' for Insightly:Module
```

**Comment by dior001** [comment]
If you're using v0.0.6 the module name has changed to resolve a conflict with an existing gem on RubyGems.org of the same name. Insightly hasn't merged the PR to update the module name yet in their GitHub repo. Anyway to fix the problem try:

```
Insightly2.api_key = "test"
```

https://github.com/scienceexchange/ruby

Let me know if you're still having issues.
Cheers

**Comment by jancel** [comment]
Thanks. Updating to insightly 2 did the job.

```
gem 'insightly2'

...


Insightly2.api_key = "test"
```
